[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roc-mcs"
version = "0.1.0"
description = "ROC analysis pipeline for MCS files"
requires-python = ">=3.9"

dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "openpyxl"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]