[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "roc-mcs"
version = "0.1.0"
description = "Rocking curve analysis for ORTEC MCS measurements"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "openpyxl",
    "PyYAML"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
roc-mcs = "roc_mcs.cli:main"